"""Build assets/css/thln-wp-editor.css from thln-wp.css.

Inside the block editor the page body is <body class="editor-styles-wrapper">,
not <body class="thln">, so rules scoped to body.thln are re-scoped here.
Run after editing thln-wp.css:  python3 tools/build_editor_css.py
"""
import os, re
d = os.path.join(os.path.dirname(__file__), "..", "thln-astra-child", "assets", "css")
src = open(os.path.join(d, "thln-wp.css")).read()
out = src.replace("body.thln", "body.editor-styles-wrapper")
out = re.sub(r"\.thln-canvas ", "", out)
head = "/* GENERATED by tools/build_editor_css.py from thln-wp.css. Do not edit. */\n"
extra = """
/* Editor: Astra styles headings and body text with its own fonts */
body.editor-styles-wrapper, body.editor-styles-wrapper p, body.editor-styles-wrapper li,
body.editor-styles-wrapper :where(h1, h2, h3, h4, h5, h6) { font-family: var(--font); }
body.editor-styles-wrapper { background: var(--cream); color: var(--plum); }
"""
open(os.path.join(d, "thln-wp-editor.css"), "w").write(head + out + extra)
print("ok")
