"""Write css/tags.css from tags.py so both documents share one tag palette."""
from pathlib import Path
from tags import TAGS

lines = ["/* Generated by tools/build_tags_css.py from tools/tags.py. Do not edit. */"]
for slug, label, bg, ink in TAGS:
    lines.append(f".t-{slug}{{--tag-bg:{bg};--tag-ink:{ink}}}")
(Path(__file__).resolve().parent.parent / "css" / "tags.css").write_text("\n".join(lines) + "\n")
print("css/tags.css written")
